services:

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: trustvault
      POSTGRES_PASSWORD: "1263"
      POSTGRES_DB: au_gameforge
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # Saves DB data so it survives restarts
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    build: ./frontend
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_SERVER_URL=http://localhost:3001
    depends_on:
      - backend

  # 2. The Multiplayer Node.js Server
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "3001:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    # Run server with nodemon or node --watch for live reloading
    command: npm run dev
    environment:
      - CLIENT_ORIGIN=http://localhost:3000
      - DATABASE_HOST=db
    depends_on:
      - db

volumes:
  pgdata: