BEGIN;

ALTER TABLE guest_users
    ADD COLUMN IF NOT EXISTS avatar_key VARCHAR(100) NOT NULL DEFAULT 'default_avatar',
    ADD COLUMN IF NOT EXISTS bio VARCHAR(160) NOT NULL DEFAULT '';

ALTER TABLE guest_users
    ALTER COLUMN bio TYPE VARCHAR(160) USING LEFT(bio, 160),
    ALTER COLUMN bio SET DEFAULT '',
    ALTER COLUMN bio SET NOT NULL;

COMMIT;
